In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

result = array1 + array2

print(result)


[5 7 9]


In [1]:
import numpy as np

array1 = np.array([100, 2, 3])
array2 = np.array([4, 5, 6])

result = array1 + array2

print(result)


[104   7   9]


In [2]:
import numpy as np

matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8, 9], [10, 11, 12]])
matrix3 = np.array([[13, 14, 15], [16, 17, 18]])

result = matrix1 + matrix2 + matrix3

print(result)


[[21 24 27]
 [30 33 36]]
